In [1]:
import numpy as np

In [2]:
#         Write a function so that the columns of the output matrix are powers of the input vector. 

#         The order of the powers is determined by the increasing boolean argument. Specifically, 
#         when  increasing is False, the i-th output column is the input vector raised element-wise to the power  of N - i - 1.

#         HINT: Such a matrix with a geometric progression in each row is named for Alexandre Theophile Vandermonde. 

In [3]:
def Alex_Theo(a,N):
    '''give a list and number of columns
        returns a Alexandre Theophile Vandermonde matrix
    '''
    a = np.array(a)
    return np.column_stack([a**(N-(N-i)) for i in range(N)])

In [4]:
Alex_Theo([1,3,5,7],3)

array([[ 1,  1,  1],
       [ 1,  3,  9],
       [ 1,  5, 25],
       [ 1,  7, 49]], dtype=int32)

In [5]:
Alex_Theo([2,5,3,7,9,4],5)

array([[   1,    2,    4,    8,   16],
       [   1,    5,   25,  125,  625],
       [   1,    3,    9,   27,   81],
       [   1,    7,   49,  343, 2401],
       [   1,    9,   81,  729, 6561],
       [   1,    4,   16,   64,  256]], dtype=int32)

In [6]:
m = np.arange(1,5).reshape(4,1)

In [7]:
Alex_Theo(m,3)

array([[ 1,  1,  1],
       [ 1,  2,  4],
       [ 1,  3,  9],
       [ 1,  4, 16]], dtype=int32)

In [8]:
#                     Given a sequence of n values x1, x2, ..., xn and a window size k>0, 
#                     the k-th moving average of  the given sequence is defined as follows: 
#                     The moving average sequence has n-k+1 elements as shown below. 
#                     The moving averages with k=4 of a ten-value sequence (n=10) is shown below 
#                     i 1 2 3 4 5 6 7 8 9 10 
#                     ===== == == == == == == == == == == 
#                     Input 10 20 30 40 50 60 70 80 90 100  
#                     y1 25 = (10+20+30+40)/4 
#                     y2 35 = (20+30+40+50)/4 
#                     y3 45 = (30+40+50+60)/4 
#                     y4 55 = (40+50+60+70)/4 
#                     y5 65 = (50+60+70+80)/4 
#                     y6 75 = (60+70+80+90)/4 
#                     y7 85 = (70+80+90+100)/4 
#                     Thus, the moving average sequence has n-k+1=10-4+1=7 values.

#                     Question: Write a function to find moving average in an array over a window:  
#                             Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3. 

In [9]:
def mov_avg(p,k):
    '''give a list and window number
        returns a new list of moving averages
    '''
    p = np.array(p)
    l=[]
    for i in range(len(p)-k+1):
        l.append(round(np.average(p[i:i+k]),2))
    return l
    

In [10]:
mov_avg([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150],3)

[5.0, 4.67, 5.67, 6.67, 9.67, 28.67, 49.33, 72.67, 84.0, 93.33, 116.33]

In [11]:
b = np.arange(10,110,10)
mov_avg(b,4)

[25.0, 35.0, 45.0, 55.0, 65.0, 75.0, 85.0]